server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/halo-demo?useUnicode=true&characterEncoding=utf8
    username: root
    password:

halo:
  swagger:
    enabled: true
    api:
      title: halo-demo
      name: halo-demo
      description: Demo project for Halo
      version: 1.0.0
      contactName: xx.xx
      contactEmail: xx.xx@itxh.net

